[package]
name = "rouille"
version = "2.0.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tomaka/rouille"
documentation = "http://docs.rs/rouille"
description = "High-level idiomatic web framework."
readme = "README.md"
keywords = ["web", "framework", "http", "rest"]
categories = ["web-programming::http-server", "web-programming::websocket"]

[features]
default = ["gzip", "brotli"]
brotli = ["brotli2"]
gzip = ["deflate"]
ssl = ["tiny_http/ssl"]

[dependencies]
base64 = "0.7.0"
brotli2 = { version = "0.2.1", optional = true }
chrono = "0.4.0"
filetime = "0.1.10"
deflate = { version = "0.7", optional = true, features = ["gzip"] }
multipart = { version = "0.13.6", default-features = false, features = ["server"] }
rand = "0.3.11"
serde = "1"
serde_derive = "1"
serde_json = "1"
sha1 = "0.2.0"
term = "0.2"
time = "0.1.31"
tiny_http = "0.5.6"
url = "1.2"
threadpool = "1"
num_cpus = "1"

[dev-dependencies]
postgres = { version = "0.13", default-features = false }
log = "0.3"
