[package]
name = "rouille"
version = "0.3.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tomaka/rouille"
documentation = "http://docs.rs/rouille"
description = "High-level web framework"

[dependencies]
filetime = "0.1.10"
multipart = { version = "0.5.1", default-features = false, features = ["server"] }
rand = "0.3.11"
rustc-serialize = "0.3"
term = "0.2"
time = "0.1.31"
tiny_http = "0.5.0"
url = "1.2"

[dev-dependencies]
mustache = "0.6"
postgres = { version = "0.13", default-features = false }
